import 'ast.dart';
import 'type.dart';

/// Emits the AST as one readable .c file with `#line` directives.
String emitC(Program program, String sourcePath) {
  final buf = StringBuffer();
  for (final include in _collectCIncludes(program)) {
    buf.writeln('#include $include');
  }
  buf.writeln('#include <stdint.h>');
  buf.writeln('#include <stddef.h>');
  buf.writeln('#include <stdbool.h>');
  buf.writeln();
  final sliceTypes = <PrimType>{};
  for (final struct in program.structs) {
    for (final field in struct.fields) {
      _collectSliceTypes(field.resolvedType, sliceTypes);
    }
  }
  for (final func in program.funcs) {
    _collectSliceTypes(func.resolvedReturnType, sliceTypes);
    for (final param in func.params) {
      _collectSliceTypes(param.resolvedType, sliceTypes);
    }
  }
  for (final type in sliceTypes) {
    final name = _sliceCName(type);
    buf.writeln(
        'typedef struct { ${type.kind.cType} *ptr; size_t len; } $name;');
  }
  if (sliceTypes.isNotEmpty) buf.writeln();
  final fnTypes = <FnType>{};
  for (final struct in program.structs) {
    for (final field in struct.fields) {
      _collectFnTypes(field.resolvedType, fnTypes);
    }
  }
  for (final func in program.funcs) {
    _collectFnTypes(func.resolvedReturnType, fnTypes);
    for (final param in func.params) {
      _collectFnTypes(param.resolvedType, fnTypes);
    }
  }
  final orderedFnTypes = fnTypes.toList()
    ..sort((a, b) => _fnTypeDepth(a).compareTo(_fnTypeDepth(b)));
  for (final type in orderedFnTypes) {
    final name = _fnTypedefName(type);
    final ps = type.params.isEmpty
        ? 'void'
        : type.params.map(_cType).join(', ');
    buf.writeln('typedef ${_cType(type.ret)} (*$name)($ps);');
  }
  if (orderedFnTypes.isNotEmpty) buf.writeln();
  if (_programNeedsTrimFrac(program)) {
    buf.writeln('#include <stdio.h>');
    buf.writeln('#include <string.h>');
    buf.writeln(
        'static void klin_fmt_trim_frac(char *buf, size_t n, double v, int max_frac) {');
    buf.writeln('    snprintf(buf, n, "%.*f", max_frac, v);');
    buf.writeln('    size_t len = strlen(buf);');
    buf.writeln('    while (len > 0 && buf[len - 1] == \'0\') {');
    buf.writeln('        buf[--len] = \'\\0\';');
    buf.writeln('    }');
    buf.writeln('    if (len > 0 && buf[len - 1] == \'.\') {');
    buf.writeln('        buf[--len] = \'\\0\';');
    buf.writeln('    }');
    buf.writeln('}');
    buf.writeln();
  }
  if (_programNeedsTimeHost(program)) {
    _emitTimeHostHelpers(buf);
  }
  for (final struct in program.structs) {
    _line(buf, struct.pos.line, struct.sourcePath ?? sourcePath);
    buf.writeln('typedef struct {');
    for (final field in struct.fields) {
      final type = field.resolvedType;
      if (type == null)
        throw StateError('emit: missing type for field `${field.name}`');
      buf.writeln('    ${_cDecl(type, field.name)};');
    }
    buf.writeln('} ${_structCName(struct.moduleName, struct.name)};');
    buf.writeln();
  }
  final resultTypes = <ResultType>{};
  for (final struct in program.structs) {
    for (final field in struct.fields) {
      _collectResultTypes(field.resolvedType, resultTypes);
    }
  }
  for (final func in program.funcs) {
    _collectResultTypes(func.resolvedReturnType, resultTypes);
    for (final param in func.params) {
      _collectResultTypes(param.resolvedType, resultTypes);
    }
  }
  for (final type in resultTypes) {
    final ok = _cType(type.ok);
    buf.writeln('typedef struct {');
    buf.writeln('    bool is_err;');
    buf.writeln('    union { $ok ok; int32_t err; } u;');
    buf.writeln('} ${_resultCName(type.ok)};');
    buf.writeln();
  }
  if (_programNeedsMemHost(program)) {
    _emitMemHostHelpers(buf, program);
  }
  for (final func in program.funcs) {
    // `@[cheader]` + `@[cimport]`: prototype lives in a C header (`cinclude`).
    if (func.attrs.any((a) => a.name == 'cheader')) continue;
    buf.writeln('${_functionHeader(func)};');
  }
  buf.writeln();
  for (final func in program.funcs) {
    if (func.body == null) continue;
    _line(buf, func.pos.line, func.sourcePath ?? sourcePath);
    buf.writeln('${_functionHeader(func)} {');
    _emitBlock(
      buf,
      func.body!,
      func.sourcePath ?? sourcePath,
      indent: 1,
      bareReturnAsZero: func.name == 'main',
      returnCType:
          func.name == 'main' ? 'int' : _cType(func.resolvedReturnType!),
      state: _EmitState(),
    );
    if (func.name == 'main') buf.writeln('    return 0;');
    buf.writeln('}');
    buf.writeln();
  }
  return buf.toString();
}

/// Emits a C header with prototypes for `@[cexport]` functions (`--emit-h`).
String emitH(Program program, String sourcePath) {
  final exports =
      program.funcs.where((f) => f.attrs.any((a) => a.name == 'cexport')).toList();
  final guard = _headerGuard(sourcePath);
  final buf = StringBuffer();
  buf.writeln('/* Generated by klin --emit-h — do not edit. */');
  buf.writeln('#ifndef $guard');
  buf.writeln('#define $guard');
  buf.writeln();
  buf.writeln('#include <stdint.h>');
  buf.writeln('#include <stddef.h>');
  buf.writeln('#include <stdbool.h>');
  buf.writeln();

  final sliceTypes = <PrimType>{};
  final resultTypes = <ResultType>{};
  final structKeys = <String>{};
  void collectSig(KlinType? type) {
    _collectSliceTypes(type, sliceTypes);
    _collectResultTypes(type, resultTypes);
    _collectStructKeys(type, structKeys);
  }

  for (final func in exports) {
    collectSig(func.resolvedReturnType);
    for (final param in func.params) {
      collectSig(param.resolvedType);
    }
    if (func.receiver case final receiver?) {
      collectSig(receiver.resolvedType);
    }
  }

  // Fixed-point: nested struct fields may add keys (and their deps) later.
  var growing = true;
  while (growing) {
    final before = structKeys.length + sliceTypes.length + resultTypes.length;
    for (final struct in program.structs) {
      final key = '${struct.moduleName}.${struct.name}';
      if (!structKeys.contains(key)) continue;
      for (final field in struct.fields) {
        collectSig(field.resolvedType);
      }
    }
    growing =
        structKeys.length + sliceTypes.length + resultTypes.length > before;
  }

  for (final type in sliceTypes) {
    buf.writeln(
        'typedef struct { ${type.kind.cType} *ptr; size_t len; } ${_sliceCName(type)};');
  }
  if (sliceTypes.isNotEmpty) buf.writeln();

  // Emit structs so field dependencies appear before dependents.
  final emittedStructs = <String>{};
  while (emittedStructs.length < structKeys.length) {
    var progress = false;
    for (final struct in program.structs) {
      final key = '${struct.moduleName}.${struct.name}';
      if (!structKeys.contains(key) || emittedStructs.contains(key)) continue;
      final fieldDeps = <String>{};
      for (final field in struct.fields) {
        _collectStructKeys(field.resolvedType, fieldDeps);
      }
      if (!fieldDeps
          .every((dep) => !structKeys.contains(dep) || emittedStructs.contains(dep))) {
        continue;
      }
      _line(buf, struct.pos.line, struct.sourcePath ?? sourcePath);
      buf.writeln('typedef struct {');
      for (final field in struct.fields) {
        final type = field.resolvedType;
        if (type == null) {
          throw StateError('emit: missing type for field `${field.name}`');
        }
        buf.writeln('    ${_cDecl(type, field.name)};');
      }
      buf.writeln('} ${_structCName(struct.moduleName, struct.name)};');
      buf.writeln();
      emittedStructs.add(key);
      progress = true;
    }
    if (!progress) {
      // Cycle or unresolved dep — fall back to declaration order (like emitC).
      for (final struct in program.structs) {
        final key = '${struct.moduleName}.${struct.name}';
        if (!structKeys.contains(key) || emittedStructs.contains(key)) continue;
        _line(buf, struct.pos.line, struct.sourcePath ?? sourcePath);
        buf.writeln('typedef struct {');
        for (final field in struct.fields) {
          final type = field.resolvedType;
          if (type == null) {
            throw StateError('emit: missing type for field `${field.name}`');
          }
          buf.writeln('    ${_cDecl(type, field.name)};');
        }
        buf.writeln('} ${_structCName(struct.moduleName, struct.name)};');
        buf.writeln();
        emittedStructs.add(key);
      }
      break;
    }
  }

  for (final type in resultTypes) {
    final ok = _cType(type.ok);
    buf.writeln('typedef struct {');
    buf.writeln('    bool is_err;');
    buf.writeln('    union { $ok ok; int32_t err; } u;');
    buf.writeln('} ${_resultCName(type.ok)};');
    buf.writeln();
  }

  for (final func in exports) {
    _line(buf, func.pos.line, func.sourcePath ?? sourcePath);
    buf.writeln('${_functionHeader(func)};');
  }
  if (exports.isNotEmpty) buf.writeln();

  buf.writeln('#endif /* $guard */');
  return buf.toString();
}

void _collectStructKeys(KlinType? type, Set<String> output) {
  if (type == null) return;
  switch (type) {
    case StructType(:final moduleName, :final name):
      output.add('$moduleName.$name');
    case PtrType(:final pointee):
      _collectStructKeys(pointee, output);
    case ArrayType(:final elem):
      _collectStructKeys(elem, output);
    case ResultType(:final ok):
      _collectStructKeys(ok, output);
    default:
      break;
  }
}

String _headerGuard(String sourcePath) {
  final name = sourcePath.split(RegExp(r'[/\\]')).last;
  final base = name.contains('.')
      ? name.substring(0, name.lastIndexOf('.'))
      : name;
  final cleaned = base
      .toUpperCase()
      .replaceAll(RegExp(r'[^A-Z0-9]'), '_')
      .replaceAll(RegExp(r'_+'), '_')
      .replaceAll(RegExp(r'^_|_$'), '');
  final token = cleaned.isEmpty ? 'FILE' : cleaned;
  return 'KLIN_${token}_H';
}

Set<String> _collectCIncludes(Program program) {
  final includes = <String>{};
  for (final decl in [...program.structs, ...program.funcs]) {
    final attrs = switch (decl) {
      StructDecl(:final attrs) => attrs,
      FuncDecl(:final attrs) => attrs,
      _ => const <Attr>[],
    };
    for (final attr in attrs) {
      if (attr.name == 'cinclude') {
        final arg = attr.arg!;
        includes.add(arg.startsWith('<') ? arg : '"$arg"');
      }
    }
  }
  if (program.funcs.any(_callsStdio)) includes.add('<stdio.h>');
  return includes;
}

bool _callsStdio(FuncDecl func) =>
    func.body?.stmts.any(_stmtCallsStdio) ?? false;

bool _isStdioName(String? name) => name == 'puts' || name == 'printf';

bool _stmtCallsStdio(Stmt stmt) => switch (stmt) {
      CallStmt(:final callee, :final args, :final resolvedCallee) =>
        _isStdioName(callee) ||
            _isStdioName(resolvedCallee) ||
            args.any(_exprCallsStdio),
      MethodCallStmt(:final call) => _exprCallsStdio(call),
      LetStmt(:final init) => init != null && _exprCallsStdio(init),
      LetDestructureStmt(:final source) => _exprCallsStdio(source),
      LetArrayDestructureStmt(:final source) => _exprCallsStdio(source),
      AssignStmt(:final target, :final value) =>
        _exprCallsStdio(target) || _exprCallsStdio(value),
      IfStmt(:final cond, :final thenBlock, :final elseBranch) =>
        _exprCallsStdio(cond) ||
            thenBlock.stmts.any(_stmtCallsStdio) ||
            (elseBranch != null && _stmtCallsStdio(elseBranch)),
      WhileStmt(:final cond, :final body) =>
        _exprCallsStdio(cond) || body.stmts.any(_stmtCallsStdio),
      ForRangeStmt(:final start, :final endExclusive, :final body) =>
        _exprCallsStdio(start) ||
            _exprCallsStdio(endExclusive) ||
            body.stmts.any(_stmtCallsStdio),
      ForCStmt(:final initExpr, :final cond, :final postExpr, :final body) =>
        (initExpr != null && _exprCallsStdio(initExpr)) ||
            (cond != null && _exprCallsStdio(cond)) ||
            (postExpr != null && _exprCallsStdio(postExpr)) ||
            body.stmts.any(_stmtCallsStdio),
      ReturnStmt(:final value) => value != null && _exprCallsStdio(value),
      DeferStmt(:final body) => _stmtCallsStdio(body),
      BlockStmt(:final block) => block.stmts.any(_stmtCallsStdio),
      MatchStmt(:final subject, :final arms) => _exprCallsStdio(subject) ||
          arms.any((arm) => arm.body.stmts.any(_stmtCallsStdio)),
      _ => false,
    };

bool _exprCallsStdio(Expr expr) => switch (expr) {
      CallExpr(:final callee, :final args, :final resolvedCallee) =>
        _isStdioName(callee) ||
            _isStdioName(resolvedCallee) ||
            args.any(_exprCallsStdio) ||
            (args.length == 1 && args[0] is InterpolatedStringExpr),
      InterpolatedStringExpr() => true,
      MethodCallExpr(:final receiver, :final args) =>
        _exprCallsStdio(receiver) || args.any(_exprCallsStdio),
      FieldExpr(:final object) => _exprCallsStdio(object),
      IndexExpr(:final object, :final index) =>
        _exprCallsStdio(object) || _exprCallsStdio(index),
      SliceFromExpr(:final array) => _exprCallsStdio(array),
      ArrayLitExpr(:final elements) => elements.any(_exprCallsStdio),
      CastExpr(:final expr) => _exprCallsStdio(expr),
      BinaryExpr(:final left, :final right) =>
        _exprCallsStdio(left) || _exprCallsStdio(right),
      UnaryExpr(:final operand) => _exprCallsStdio(operand),
      GroupExpr(:final inner) => _exprCallsStdio(inner),
      ErrorExpr(:final code) => _exprCallsStdio(code),
      PropagateExpr(:final result) => _exprCallsStdio(result),
      OrExpr(:final result, :final fallback) => _exprCallsStdio(result) ||
          fallback.stmts.any(_stmtCallsStdio) ||
          _exprCallsStdio(fallback.value),
      StructLitExpr(:final namedFields, :final positionalFields) =>
        namedFields?.values.any(_exprCallsStdio) ??
            positionalFields!.any(_exprCallsStdio),
      MatchExpr(:final subject, :final arms) => _exprCallsStdio(subject) ||
          arms.any((arm) => _exprCallsStdio(arm.body)),
      _ => false,
    };

bool _programNeedsTrimFrac(Program program) {
  for (final func in program.funcs) {
    if (func.body != null && _blockNeedsTrimFrac(func.body!)) return true;
  }
  return false;
}

bool _programNeedsMemHost(Program program) {
  for (final func in program.funcs) {
    for (final attr in func.attrs) {
      if (attr.name == 'codename' &&
          attr.arg != null &&
          attr.arg!.startsWith('klin_mem_')) {
        return true;
      }
    }
  }
  return false;
}

Set<String> _memHostCodename(Program program) {
  final names = <String>{};
  for (final func in program.funcs) {
    for (final attr in func.attrs) {
      if (attr.name == 'codename' &&
          attr.arg != null &&
          attr.arg!.startsWith('klin_mem_')) {
        names.add(attr.arg!);
      }
    }
  }
  return names;
}

void _emitMemHostHelpers(StringBuffer buf, Program program) {
  final names = _memHostCodename(program);
  buf.writeln('#include <stdlib.h>');
  buf.writeln();
  for (final name in names) {
    if (name == 'klin_mem_alloc_u8') {
      final res = _resultCName(const SliceType(PrimType(PrimKind.u8)));
      final slice = _sliceCName(const PrimType(PrimKind.u8));
      buf.writeln('$res klin_mem_alloc_u8(int32_t n) {');
      buf.writeln('    $res r;');
      buf.writeln('    if (n < 0) { r.is_err = true; r.u.err = 1; return r; }');
      buf.writeln('    if (n == 0) {');
      buf.writeln('        r.is_err = false;');
      buf.writeln('        r.u.ok = ($slice){ NULL, 0 };');
      buf.writeln('        return r;');
      buf.writeln('    }');
      buf.writeln('    void *p = malloc((size_t)n);');
      buf.writeln('    if (p == NULL) { r.is_err = true; r.u.err = 2; return r; }');
      buf.writeln('    r.is_err = false;');
      buf.writeln('    r.u.ok = ($slice){ (uint8_t *)p, (size_t)n };');
      buf.writeln('    return r;');
      buf.writeln('}');
      buf.writeln();
    } else if (name == 'klin_mem_free_u8') {
      final slice = _sliceCName(const PrimType(PrimKind.u8));
      buf.writeln('void klin_mem_free_u8($slice buf) {');
      buf.writeln('    free(buf.ptr);');
      buf.writeln('}');
      buf.writeln();
    } else if (name == 'klin_mem_alloc_i32') {
      final res = _resultCName(const SliceType(PrimType(PrimKind.i32)));
      final slice = _sliceCName(const PrimType(PrimKind.i32));
      buf.writeln('$res klin_mem_alloc_i32(int32_t n) {');
      buf.writeln('    $res r;');
      buf.writeln('    if (n < 0) { r.is_err = true; r.u.err = 1; return r; }');
      buf.writeln('    if (n == 0) {');
      buf.writeln('        r.is_err = false;');
      buf.writeln('        r.u.ok = ($slice){ NULL, 0 };');
      buf.writeln('        return r;');
      buf.writeln('    }');
      buf.writeln(
          '    if ((size_t)n > SIZE_MAX / sizeof(int32_t)) {');
      buf.writeln('        r.is_err = true; r.u.err = 2; return r;');
      buf.writeln('    }');
      buf.writeln(
          '    void *p = malloc((size_t)n * sizeof(int32_t));');
      buf.writeln('    if (p == NULL) { r.is_err = true; r.u.err = 2; return r; }');
      buf.writeln('    r.is_err = false;');
      buf.writeln('    r.u.ok = ($slice){ (int32_t *)p, (size_t)n };');
      buf.writeln('    return r;');
      buf.writeln('}');
      buf.writeln();
    } else if (name == 'klin_mem_free_i32') {
      final slice = _sliceCName(const PrimType(PrimKind.i32));
      buf.writeln('void klin_mem_free_i32($slice buf) {');
      buf.writeln('    free(buf.ptr);');
      buf.writeln('}');
      buf.writeln();
    } else if (name == 'klin_mem_empty_u8') {
      final slice = _sliceCName(const PrimType(PrimKind.u8));
      buf.writeln('$slice klin_mem_empty_u8(void) {');
      buf.writeln('    return ($slice){ NULL, 0 };');
      buf.writeln('}');
      buf.writeln();
    } else if (name == 'klin_mem_empty_i32') {
      final slice = _sliceCName(const PrimType(PrimKind.i32));
      buf.writeln('$slice klin_mem_empty_i32(void) {');
      buf.writeln('    return ($slice){ NULL, 0 };');
      buf.writeln('}');
      buf.writeln();
    }
  }
}

bool _programNeedsTimeHost(Program program) {
  const names = {
    'klin_time_wall_ns',
    'klin_time_mono_ns',
    'klin_time_format',
    'klin_time_parse',
    'klin_time_parse_iso',
    'klin_time_add_date',
  };
  for (final func in program.funcs) {
    for (final attr in func.attrs) {
      if (attr.name == 'codename' && attr.arg != null && names.contains(attr.arg)) {
        return true;
      }
    }
  }
  return false;
}

void _emitTimeHostHelpers(StringBuffer buf) {
  buf.writeln('#include <time.h>');
  buf.writeln('#include <stdio.h>');
  buf.writeln('#include <string.h>');
  buf.writeln('#include <errno.h>');
  buf.writeln();
  buf.writeln('int64_t klin_time_wall_ns(void) {');
  buf.writeln('    struct timespec ts;');
  buf.writeln('    if (clock_gettime(CLOCK_REALTIME, &ts) != 0) return 0;');
  buf.writeln(
      '    return (int64_t)ts.tv_sec * 1000000000LL + (int64_t)ts.tv_nsec;');
  buf.writeln('}');
  buf.writeln();
  buf.writeln('int64_t klin_time_mono_ns(void) {');
  buf.writeln('    struct timespec ts;');
  buf.writeln('    if (clock_gettime(CLOCK_MONOTONIC, &ts) != 0) return 0;');
  buf.writeln(
      '    return (int64_t)ts.tv_sec * 1000000000LL + (int64_t)ts.tv_nsec;');
  buf.writeln('}');
  buf.writeln();
  buf.writeln(
      'int32_t klin_time_format(uint8_t *buf, int32_t buflen, const char *fmt, int64_t unix_ns) {');
  buf.writeln('    if (buf == NULL || buflen <= 0 || fmt == NULL) return -1;');
  buf.writeln('    time_t sec = (time_t)(unix_ns / 1000000000LL);');
  buf.writeln('    struct tm tm;');
  buf.writeln('    if (gmtime_r(&sec, &tm) == NULL) return -1;');
  buf.writeln(
      '    size_t n = strftime((char *)buf, (size_t)buflen, fmt, &tm);');
  buf.writeln('    if (n == 0) return -1;');
  buf.writeln('    return (int32_t)n;');
  buf.writeln('}');
  buf.writeln();
  buf.writeln(
      'static int32_t klin_time_from_tm(int64_t *out_ns, struct tm *tm) {');
  buf.writeln('    errno = 0;');
  buf.writeln('    time_t sec = timegm(tm);');
  // time_t -1 is also a valid UTC instant (1969-12-31 23:59:59); only fail on errno.
  buf.writeln('    if (sec == (time_t)-1 && errno != 0) return 2;');
  buf.writeln('    *out_ns = (int64_t)sec * 1000000000LL;');
  buf.writeln('    return 0;');
  buf.writeln('}');
  buf.writeln();
  buf.writeln(
      'int32_t klin_time_parse_iso(int64_t *out_ns, const char *s) {');
  buf.writeln('    if (out_ns == NULL || s == NULL) return 1;');
  buf.writeln('    int y = 0, mo = 0, d = 0, h = 0, mi = 0, sec = 0;');
  buf.writeln('    int consumed = 0;');
  buf.writeln(
      '    if (sscanf(s, "%d-%d-%dT%d:%d:%dZ%n", &y, &mo, &d, &h, &mi, &sec, &consumed) == 6) {');
  buf.writeln('        if (s[consumed] != \'\\0\') return 1;');
  buf.writeln(
      '    } else if (sscanf(s, "%d-%d-%d%n", &y, &mo, &d, &consumed) == 3) {');
  buf.writeln('        if (s[consumed] != \'\\0\') return 1;');
  buf.writeln('        h = 0; mi = 0; sec = 0;');
  buf.writeln('    } else {');
  buf.writeln('        return 1;');
  buf.writeln('    }');
  buf.writeln('    if (mo < 1 || mo > 12 || d < 1 || d > 31) return 1;');
  buf.writeln('    struct tm tm;');
  buf.writeln('    memset(&tm, 0, sizeof(tm));');
  buf.writeln('    tm.tm_year = y - 1900;');
  buf.writeln('    tm.tm_mon = mo - 1;');
  buf.writeln('    tm.tm_mday = d;');
  buf.writeln('    tm.tm_hour = h;');
  buf.writeln('    tm.tm_min = mi;');
  buf.writeln('    tm.tm_sec = sec;');
  buf.writeln('    return klin_time_from_tm(out_ns, &tm);');
  buf.writeln('}');
  buf.writeln();
  buf.writeln(
      'int32_t klin_time_parse(int64_t *out_ns, const char *fmt, const char *s) {');
  buf.writeln('    if (out_ns == NULL || fmt == NULL || s == NULL) return 1;');
  buf.writeln('    struct tm tm;');
  buf.writeln('    memset(&tm, 0, sizeof(tm));');
  buf.writeln('    const char *end = strptime(s, fmt, &tm);');
  buf.writeln('    if (end == NULL || *end != \'\\0\') return 1;');
  buf.writeln('    return klin_time_from_tm(out_ns, &tm);');
  buf.writeln('}');
  buf.writeln();
  // Go-style AddDate on UTC civil calendar; preserves sub-second ns.
  buf.writeln(
      'int32_t klin_time_add_date(int64_t *out_ns, int64_t unix_ns, int32_t years, int32_t months, int32_t days) {');
  buf.writeln('    if (out_ns == NULL) return 1;');
  buf.writeln('    int64_t sec = unix_ns / 1000000000LL;');
  buf.writeln('    int64_t frac = unix_ns % 1000000000LL;');
  buf.writeln('    if (frac < 0) {');
  buf.writeln('        frac += 1000000000LL;');
  buf.writeln('        sec -= 1;');
  buf.writeln('    }');
  buf.writeln('    time_t tsec = (time_t)sec;');
  buf.writeln('    struct tm tm;');
  buf.writeln('    if (gmtime_r(&tsec, &tm) == NULL) return 1;');
  buf.writeln('    tm.tm_year += (int)years;');
  buf.writeln('    tm.tm_mon += (int)months;');
  buf.writeln('    tm.tm_mday += (int)days;');
  buf.writeln('    tm.tm_isdst = 0;');
  buf.writeln('    int32_t rc = klin_time_from_tm(out_ns, &tm);');
  buf.writeln('    if (rc != 0) return rc;');
  buf.writeln('    *out_ns += frac;');
  buf.writeln('    return 0;');
  buf.writeln('}');
  buf.writeln();
}

bool _blockNeedsTrimFrac(Block block) {
  for (final stmt in block.stmts) {
    if (_stmtNeedsTrimFrac(stmt)) return true;
  }
  return false;
}

bool _stmtNeedsTrimFrac(Stmt stmt) => switch (stmt) {
      CallStmt(:final args) => args.any(_exprNeedsTrimFrac),
      LetStmt(:final init) => init != null && _exprNeedsTrimFrac(init),
      LetDestructureStmt(:final source) => _exprNeedsTrimFrac(source),
      LetArrayDestructureStmt(:final source) => _exprNeedsTrimFrac(source),
      AssignStmt(:final value) => _exprNeedsTrimFrac(value),
      ReturnStmt(:final value) => value != null && _exprNeedsTrimFrac(value),
      IfStmt(:final thenBlock, :final elseBranch, :final cond) =>
        _exprNeedsTrimFrac(cond) ||
            _blockNeedsTrimFrac(thenBlock) ||
            (elseBranch != null && _stmtNeedsTrimFrac(elseBranch)),
      WhileStmt(:final body, :final cond) =>
        _exprNeedsTrimFrac(cond) || _blockNeedsTrimFrac(body),
      ForRangeStmt(:final body) => _blockNeedsTrimFrac(body),
      ForCStmt(:final body) => _blockNeedsTrimFrac(body),
      BlockStmt(:final block) => _blockNeedsTrimFrac(block),
      DeferStmt(:final body) => _stmtNeedsTrimFrac(body),
      MethodCallStmt(:final call) => _exprNeedsTrimFrac(call),
      MatchStmt(:final subject, :final arms) => _exprNeedsTrimFrac(subject) ||
          arms.any((arm) => _blockNeedsTrimFrac(arm.body)),
      _ => false,
    };

bool _exprNeedsTrimFrac(Expr expr) => switch (expr) {
      InterpolatedStringExpr(:final parts) => parts.any(
          (p) => p is InterpSlot && p.trimFrac,
        ),
      CallExpr(:final args) => args.any(_exprNeedsTrimFrac),
      BinaryExpr(:final left, :final right) =>
        _exprNeedsTrimFrac(left) || _exprNeedsTrimFrac(right),
      UnaryExpr(:final operand) => _exprNeedsTrimFrac(operand),
      GroupExpr(:final inner) => _exprNeedsTrimFrac(inner),
      MethodCallExpr(:final receiver, :final args) =>
        _exprNeedsTrimFrac(receiver) || args.any(_exprNeedsTrimFrac),
      MatchExpr(:final subject, :final arms) => _exprNeedsTrimFrac(subject) ||
          arms.any((arm) => _exprNeedsTrimFrac(arm.body)),
      _ => false,
    };

void _emitInterpPrintf(
  StringBuffer buf,
  InterpolatedStringExpr interp, {
  required int indent,
  required _ExprCtx ctx,
  required _EmitState state,
}) {
  final pad = '    ' * indent;
  final prepared = _prepareInterpPrintf(interp, ctx, state, pad, buf);
  final args = prepared.argExprs.isEmpty
      ? ''
      : ', ${prepared.argExprs.join(', ')}';
  buf.writeln('${pad}printf("${prepared.fmt}"$args);');
}

String _emitInterpPrintfExpr(InterpolatedStringExpr interp, _ExprCtx ctx) {
  // Expression context: declare temps into ctx.buf, return printf(...) as expr.
  final pad = '    ' * ctx.indent;
  final prepared =
      _prepareInterpPrintf(interp, ctx, ctx.state, pad, ctx.buf);
  final args = prepared.argExprs.isEmpty
      ? ''
      : ', ${prepared.argExprs.join(', ')}';
  return 'printf("${prepared.fmt}"$args)';
}

({String fmt, List<String> argExprs}) _prepareInterpPrintf(
  InterpolatedStringExpr interp,
  _ExprCtx ctx,
  _EmitState state,
  String pad,
  StringBuffer buf,
) {
  final fmt = StringBuffer();
  final argExprs = <String>[];
  for (final part in interp.parts) {
    switch (part) {
      case InterpText(:final text):
        // `%` in literal text must be `%%` inside a printf format string.
        fmt.write(_escapeC(text).replaceAll('%', '%%'));
      case InterpSlot(
          :final expr,
          :final printfSpec,
          :final trimFrac,
          :final trimFracDigits
        ):
        if (trimFrac) {
          final name = state.nextInterpBuf();
          buf.writeln('${pad}char $name[64];');
          buf.writeln(
            '${pad}klin_fmt_trim_frac($name, sizeof($name), '
            '(double)(${_emitExpr(expr, ctx)}), $trimFracDigits);',
          );
          fmt.write('%s');
          argExprs.add(name);
        } else {
          fmt.write(printfSpec ?? '%s');
          argExprs.add(_emitExpr(expr, ctx));
        }
    }
  }
  if (interp.appendNewline) {
    fmt.write('\\n');
  }
  return (fmt: fmt.toString(), argExprs: argExprs);
}

String _functionHeader(FuncDecl func) {
  if (func.name == 'main') return 'int main(void)';
  final returnType = func.resolvedReturnType;
  if (returnType == null) {
    throw StateError('emit: missing return type for function `${func.name}`');
  }
  final params = <String>[
    if (func.receiver case final receiver?)
      '${_cType(receiver.resolvedType!)}${receiver.isMut ? ' *' : ' '}${receiver.name}',
    ...func.params.map((param) {
      final type = param.resolvedType;
      if (type == null) {
        throw StateError('emit: missing type for parameter `${param.name}`');
      }
      return _cDecl(type, param.name);
    }),
  ];
  final codename = func.attrs
      .where((attr) => attr.name == 'codename')
      .map((attr) => attr.arg!)
      .firstOrNull;
  final name = func.name == 'main'
      ? 'main'
      : codename ??
          (func.receiver == null
              ? _freeCName(func.moduleName, func.name)
              : _methodCName(
                  func.moduleName,
                  _receiverTypeName(func.receiver!),
                  func.name,
                ));
  final staticPrefix = !func.isPub &&
          func.name != 'main' &&
          codename == null &&
          func.body != null
      ? 'static '
      : '';
  return '$staticPrefix${_cType(returnType)} $name(${params.isEmpty ? 'void' : params.join(', ')})';
}

String _receiverTypeName(Receiver receiver) => receiver.typeName.contains('.')
    ? receiver.typeName.split('.').last
    : receiver.typeName;

String _cType(KlinType type) => switch (type) {
      PrimType(:final kind) => kind.cType,
      VoidType() => 'void',
      StrType() => 'const char*',
      StructType(:final moduleName, :final name) =>
        _structCName(moduleName, name),
      PtrType(:final pointee, :final isVolatile) =>
        '${isVolatile ? 'volatile ' : ''}${_cType(pointee)} *',
      ArrayType(:final elem) => _cType(elem),
      SliceType(:final elem) => _sliceCName(elem),
      ResultType(:final ok) => _resultCName(ok),
      FnType(:final params, :final ret) => _fnTypedefName(FnType(params, ret)),
      _ => throw StateError('emit: type `${type.displayName}` has no C type'),
    };

String _cDecl(KlinType type, String name) => switch (type) {
      ArrayType(:final elem, :final len) => '${_cType(elem)} $name[$len]',
      FnType(:final params, :final ret) => () {
          final ps = params.isEmpty
              ? 'void'
              : params.map(_cType).join(', ');
          return '${_cType(ret)} (*$name)($ps)';
        }(),
      _ => '${_cType(type)} $name',
    };

String _fnTypedefName(FnType type) {
  final ps = type.params.map(_typeToken).join('_');
  final ret = _typeToken(type.ret);
  return ps.isEmpty ? 'klin_fn_void_$ret' : 'klin_fn_${ps}__$ret';
}

int _fnTypeDepth(FnType type) {
  var depth = 0;
  for (final p in type.params) {
    if (p is FnType) {
      final d = _fnTypeDepth(p) + 1;
      if (d > depth) depth = d;
    }
  }
  if (type.ret is FnType) {
    final d = _fnTypeDepth(type.ret as FnType) + 1;
    if (d > depth) depth = d;
  }
  return depth;
}

String _sliceCName(PrimType elem) => 'klin_slice_${elem.kind.klinName}';

void _collectSliceTypes(KlinType? type, Set<PrimType> output) {
  if (type case SliceType(:final elem)) output.add(elem);
  if (type case PtrType(:final pointee)) _collectSliceTypes(pointee, output);
  if (type case ArrayType(:final elem)) _collectSliceTypes(elem, output);
  if (type case ResultType(:final ok)) _collectSliceTypes(ok, output);
  if (type case FnType(:final params, :final ret)) {
    for (final p in params) {
      _collectSliceTypes(p, output);
    }
    _collectSliceTypes(ret, output);
  }
}

void _collectFnTypes(KlinType? type, Set<FnType> output) {
  if (type case FnType()) {
    output.add(type);
    for (final p in type.params) {
      _collectFnTypes(p, output);
    }
    _collectFnTypes(type.ret, output);
  }
  if (type case PtrType(:final pointee)) _collectFnTypes(pointee, output);
  if (type case ArrayType(:final elem)) _collectFnTypes(elem, output);
  if (type case ResultType(:final ok)) _collectFnTypes(ok, output);
}

void _collectResultTypes(KlinType? type, Set<ResultType> output) {
  if (type case ResultType(:final ok)) {
    output.add(type);
    _collectResultTypes(ok, output);
  }
  if (type case PtrType(:final pointee)) _collectResultTypes(pointee, output);
  if (type case ArrayType(:final elem)) _collectResultTypes(elem, output);
  if (type case FnType(:final params, :final ret)) {
    for (final p in params) {
      _collectResultTypes(p, output);
    }
    _collectResultTypes(ret, output);
  }
}

String _resultCName(KlinType ok) => 'klin_res_${_typeToken(ok)}';

String _typeToken(KlinType type) => switch (type) {
      PrimType(:final kind) => kind.klinName,
      VoidType() => 'void',
      StructType(:final moduleName, :final name) =>
        _structCName(moduleName, name),
      SliceType(:final elem) => _sliceCName(elem),
      PtrType(:final pointee, :final isMut, :final isVolatile) =>
        '${isMut ? 'mut_' : ''}${isVolatile ? 'volatile_' : ''}ptr_${_typeToken(pointee)}',
      ArrayType(:final elem, :final len) => 'arr${len}_${_typeToken(elem)}',
      ResultType(:final ok) => 'res_${_typeToken(ok)}',
      FnType(:final params, :final ret) =>
        'fn_${params.map(_typeToken).join('_')}_${_typeToken(ret)}',
      StrType() => 'str',
      _ =>
        throw StateError('emit: missing type token for `${type.displayName}`'),
    };

final class _DeferFrame {
  /// Defer bodies registered in encounter order, not from the whole block in advance.
  final List<Stmt> defers = [];
  final bool isLoopBody;

  _DeferFrame({this.isLoopBody = false});
}

final class _EmitState {
  final List<_DeferFrame> deferStack = [];
  int _returnTemp = 0;
  int _valueTemp = 0;
  int _interpTemp = 0;

  String nextReturnTemp() => 'klin_ret_${_returnTemp++}';
  String nextValueTemp() => 'klin_val_${_valueTemp++}';
  String nextInterpBuf() => '_klin_i${_interpTemp++}';
}

final class _ExprCtx {
  final StringBuffer buf;
  final String sourcePath;
  final int indent;
  final bool bareReturnAsZero;
  final String returnCType;
  final _EmitState state;

  _ExprCtx({
    required this.buf,
    required this.sourcePath,
    required this.indent,
    required this.bareReturnAsZero,
    required this.returnCType,
    required this.state,
  });
}

void _emitValueAssignment(
  StringBuffer buf, {
  required String target,
  required KlinType targetType,
  required Expr value,
  required String sourcePath,
  required int indent,
  required bool bareReturnAsZero,
  required String returnCType,
  required _EmitState state,
}) {
  final ctx = _ExprCtx(
    buf: buf,
    sourcePath: sourcePath,
    indent: indent,
    bareReturnAsZero: bareReturnAsZero,
    returnCType: returnCType,
    state: state,
  );
  final pad = '    ' * indent;
  if (value case PropagateExpr(:final result)) {
    final temp = _emitPropagate(result, ctx);
    buf.writeln('$pad$target = $temp.u.ok;');
    return;
  }
  if (value case OrExpr(:final result, :final fallback)) {
    final resultType = result.resolvedType;
    if (resultType is! ResultType) {
      throw StateError('emit: `or` without a result type');
    }
    final temp = state.nextValueTemp();
    buf.writeln('$pad${_cType(resultType)} $temp = ${_emitExpr(result, ctx)};');
    buf.writeln('${pad}if ($temp.is_err) {');
    final innerPad = '    ' * (indent + 1);
    buf.writeln('${innerPad}int32_t err = $temp.u.err;');
    for (final stmt in fallback.stmts) {
      _emitStmt(
        buf,
        stmt,
        sourcePath,
        indent: indent + 1,
        pad: innerPad,
        bareReturnAsZero: bareReturnAsZero,
        returnCType: returnCType,
        state: state,
      );
    }
    _emitValueAssignment(
      buf,
      target: target,
      targetType: targetType,
      value: fallback.value,
      sourcePath: sourcePath,
      indent: indent + 1,
      bareReturnAsZero: bareReturnAsZero,
      returnCType: returnCType,
      state: state,
    );
    buf.writeln('$pad} else {');
    buf.writeln('${innerPad}$target = $temp.u.ok;');
    buf.writeln('$pad}');
    return;
  }
  buf.writeln('$pad$target = ${_emitExpr(value, ctx)};');
}

String _emitPropagate(Expr result, _ExprCtx ctx) {
  final resultType = result.resolvedType;
  if (resultType is! ResultType) {
    throw StateError('emit: propagation without a result type');
  }
  final pad = '    ' * ctx.indent;
  final temp = ctx.state.nextValueTemp();
  ctx.buf
      .writeln('$pad${_cType(resultType)} $temp = ${_emitExpr(result, ctx)};');
  ctx.buf.writeln('${pad}if ($temp.is_err) {');
  _emitExitCleanups(
    ctx.buf,
    ctx.state.deferStack,
    ctx.sourcePath,
    indent: ctx.indent + 1,
    bareReturnAsZero: ctx.bareReturnAsZero,
    returnCType: ctx.returnCType,
    state: ctx.state,
  );
  ctx.buf.writeln('${'    ' * (ctx.indent + 1)}return $temp;');
  ctx.buf.writeln('$pad}');
  return temp;
}

void _emitBlock(
  StringBuffer buf,
  Block block,
  String sourcePath, {
  required int indent,
  required bool bareReturnAsZero,
  required String returnCType,
  required _EmitState state,
  bool isLoopBody = false,
}) {
  final pad = '    ' * indent;
  final frame = _DeferFrame(isLoopBody: isLoopBody);
  state.deferStack.add(frame);
  for (final stmt in block.stmts) {
    _emitStmt(
      buf,
      stmt,
      sourcePath,
      indent: indent,
      pad: pad,
      bareReturnAsZero: bareReturnAsZero,
      returnCType: returnCType,
      state: state,
    );
  }
  _emitFrameCleanups(
    buf,
    frame,
    sourcePath,
    indent: indent,
    bareReturnAsZero: bareReturnAsZero,
    returnCType: returnCType,
    state: state,
  );
  state.deferStack.removeLast();
}

void _emitStmt(
  StringBuffer buf,
  Stmt stmt,
  String sourcePath, {
  required int indent,
  required String pad,
  required bool bareReturnAsZero,
  required String returnCType,
  required _EmitState state,
}) {
  final ctx = _ExprCtx(
    buf: buf,
    sourcePath: sourcePath,
    indent: indent,
    bareReturnAsZero: bareReturnAsZero,
    returnCType: returnCType,
    state: state,
  );
  switch (stmt) {
    case AsmStmt(:final code, :final pos):
      _line(buf, pos.line, sourcePath);
      buf.writeln('${pad}asm volatile("${_escapeC(code)}");');

    case LetStmt(:final name, :final init, :final pos, :final resolvedType):
      _line(buf, pos.line, sourcePath);
      final ty = resolvedType;
      if (ty == null) {
        throw StateError('emit: missing type for `$name` — run the checker');
      }
      if (init != null) {
        if (init is OrExpr || init is PropagateExpr) {
          buf.writeln('$pad${_cDecl(ty, name)};');
          _emitValueAssignment(
            buf,
            target: name,
            targetType: ty,
            value: init,
            sourcePath: sourcePath,
            indent: indent,
            bareReturnAsZero: bareReturnAsZero,
            returnCType: returnCType,
            state: state,
          );
        } else if (init is MatchExpr) {
          buf.writeln('$pad${_cDecl(ty, name)};');
          _emitMatchAssign(
            buf,
            target: name,
            targetType: ty,
            match: init,
            sourcePath: sourcePath,
            indent: indent,
            bareReturnAsZero: bareReturnAsZero,
            returnCType: returnCType,
            state: state,
          );
        } else {
          buf.writeln('$pad${_cDecl(ty, name)} = ${_emitExpr(init, ctx)};');
        }
      } else {
        final zero = switch (ty) {
          PrimType(:final kind) => kind.cZero,
          PtrType() => 'NULL',
          FnType() => 'NULL',
          ArrayType() => '{0}',
          SliceType() => '{ NULL, 0 }',
          StructType() => '{0}',
          StrType() => 'NULL',
          ResultType() => '{0}',
          _ => throw StateError('emit: missing default value for `$name`'),
        };
        buf.writeln('$pad${_cDecl(ty, name)} = $zero;');
      }

    case LetDestructureStmt(
        :final fields,
        :final binds,
        :final source,
        :final pos,
        :final sourceType,
        :final fieldTypes
      ):
      _line(buf, pos.line, sourcePath);
      final st = sourceType!;
      final fts = fieldTypes!;
      // Evaluate the source once. A plain name needs no temp; any other
      // expression is copied into a temp so it is not re-evaluated per field.
      final String access;
      if (source is NameExpr) {
        access = _emitExpr(source, ctx) +
            (_exprIsPtrReceiver(source) ? '->' : '.');
      } else {
        final tmp = state.nextValueTemp();
        buf.writeln('$pad${_cDecl(st, tmp)} = ${_emitExpr(source, ctx)};');
        access = '$tmp.';
      }
      for (var i = 0; i < fields.length; i++) {
        buf.writeln(
            '$pad${_cDecl(fts[i], binds[i])} = $access${fields[i]};');
      }

    case LetArrayDestructureStmt(
        :final names,
        :final source,
        :final pos,
        :final elemType
      ):
      _line(buf, pos.line, sourcePath);
      final et = elemType!;
      if (source is ArrayLitExpr) {
        // Evaluate each bound element into a fresh temp before binding, so a
        // swap like `let [a, b] = [b, a]` reads the outer values, not new
        // bindings. `_` positions are skipped (not evaluated, not bound).
        final temps = List<String?>.filled(names.length, null);
        for (var i = 0; i < names.length; i++) {
          if (names[i] == null) continue;
          final t = state.nextValueTemp();
          temps[i] = t;
          buf.writeln(
              '$pad${_cDecl(et, t)} = ${_emitExpr(source.elements[i], ctx)};');
        }
        for (var i = 0; i < names.length; i++) {
          final name = names[i];
          if (name == null) continue;
          buf.writeln('$pad${_cDecl(et, name)} = ${temps[i]};');
        }
      } else {
        // A plain array variable is indexed in place. If a binding shadows the
        // source name, capture the array via a pointer first so later reads do
        // not index a freshly-declared scalar.
        final base = _emitExpr(source, ctx);
        final String indexed;
        if (source is NameExpr && names.contains(source.name)) {
          final tmp = state.nextValueTemp();
          buf.writeln('$pad${_cType(et)} *$tmp = $base;');
          indexed = tmp;
        } else {
          indexed = base;
        }
        for (var i = 0; i < names.length; i++) {
          final name = names[i];
          if (name == null) continue; // `_` skip
          buf.writeln('$pad${_cDecl(et, name)} = $indexed[$i];');
        }
      }

    case AssignStmt(:final target, :final value, :final pos):
      _line(buf, pos.line, sourcePath);
      if (value is OrExpr || value is PropagateExpr) {
        _emitValueAssignment(
          buf,
          target: _emitExpr(target, ctx),
          targetType: target.resolvedType!,
          value: value,
          sourcePath: sourcePath,
          indent: indent,
          bareReturnAsZero: bareReturnAsZero,
          returnCType: returnCType,
          state: state,
        );
      } else if (value is MatchExpr) {
        _emitMatchAssign(
          buf,
          target: _emitExpr(target, ctx),
          targetType: target.resolvedType!,
          match: value,
          sourcePath: sourcePath,
          indent: indent,
          bareReturnAsZero: bareReturnAsZero,
          returnCType: returnCType,
          state: state,
        );
      } else {
        buf.writeln(
            '$pad${_emitExpr(target, ctx)} = ${_emitExpr(value, ctx)};');
      }

    case CallStmt(
        :final callee,
        :final args,
        :final pos,
        :final resolvedCallee
      ):
      _line(buf, pos.line, sourcePath);
      if (args.length == 1 && args[0] is InterpolatedStringExpr) {
        _emitInterpPrintf(
          buf,
          args[0] as InterpolatedStringExpr,
          indent: indent,
          ctx: ctx,
          state: state,
        );
      } else {
        final argList = args.map((arg) => _emitExpr(arg, ctx)).join(', ');
        buf.writeln('$pad${resolvedCallee ?? callee}($argList);');
      }

    case MethodCallStmt(:final call):
      _line(buf, call.pos.line, sourcePath);
      buf.writeln('$pad${_emitExpr(call, ctx)};');

    case IfStmt(:final cond, :final thenBlock, :final elseBranch, :final pos):
      _line(buf, pos.line, sourcePath);
      buf.writeln('${pad}if (${_emitExpr(cond, ctx)}) {');
      _emitBlock(
        buf,
        thenBlock,
        sourcePath,
        indent: indent + 1,
        bareReturnAsZero: bareReturnAsZero,
        returnCType: returnCType,
        state: state,
      );
      _emitElse(
        buf,
        elseBranch,
        sourcePath,
        indent: indent,
        pad: pad,
        bareReturnAsZero: bareReturnAsZero,
        returnCType: returnCType,
        state: state,
      );

    case WhileStmt(:final cond, :final body, :final pos):
      _line(buf, pos.line, sourcePath);
      buf.writeln('${pad}while (${_emitExpr(cond, ctx)}) {');
      _emitBlock(
        buf,
        body,
        sourcePath,
        indent: indent + 1,
        bareReturnAsZero: bareReturnAsZero,
        returnCType: returnCType,
        state: state,
        isLoopBody: true,
      );
      buf.writeln('$pad}');

    case ForRangeStmt(
        :final name,
        :final start,
        :final endExclusive,
        :final body,
        :final pos,
        :final resolvedType
      ):
      _line(buf, pos.line, sourcePath);
      final ty = resolvedType;
      if (ty is! PrimType) {
        throw StateError('emit: missing type for loop variable `$name`');
      }
      buf.writeln(
        '${pad}for (${ty.kind.cType} $name = ${_emitExpr(start, ctx)}; '
        '$name < ${_emitExpr(endExclusive, ctx)}; $name++) {',
      );
      _emitBlock(
        buf,
        body,
        sourcePath,
        indent: indent + 1,
        bareReturnAsZero: bareReturnAsZero,
        returnCType: returnCType,
        state: state,
        isLoopBody: true,
      );
      buf.writeln('$pad}');

    case ForCStmt(
        :final initName,
        :final initExpr,
        :final cond,
        :final postName,
        :final postExpr,
        :final body,
        :final pos,
        :final resolvedInitType
      ):
      _line(buf, pos.line, sourcePath);
      final initPart = () {
        if (initName == null || initExpr == null) return '';
        final ty = resolvedInitType;
        if (ty is! PrimType) {
          throw StateError('emit: missing type for initializer `$initName`');
        }
        return '${ty.kind.cType} $initName = ${_emitExpr(initExpr, ctx)}';
      }();
      final condPart = cond == null ? '' : _emitExpr(cond, ctx);
      final postPart = (postName != null && postExpr != null)
          ? '$postName = ${_emitExpr(postExpr, ctx)}'
          : '';
      buf.writeln('${pad}for ($initPart; $condPart; $postPart) {');
      _emitBlock(
        buf,
        body,
        sourcePath,
        indent: indent + 1,
        bareReturnAsZero: bareReturnAsZero,
        returnCType: returnCType,
        state: state,
        isLoopBody: true,
      );
      buf.writeln('$pad}');

    case ReturnStmt(:final value, :final pos):
      _line(buf, pos.line, sourcePath);
      if (value == null) {
        _emitExitCleanups(
          buf,
          state.deferStack,
          sourcePath,
          indent: indent,
          bareReturnAsZero: bareReturnAsZero,
          returnCType: returnCType,
          state: state,
        );
        buf.writeln(bareReturnAsZero ? '${pad}return 0;' : '${pad}return;');
      } else {
        if (value is PropagateExpr) {
          final propagated = _emitPropagate(value.result, ctx);
          final resultType = value.result.resolvedType! as ResultType;
          final temp = state.nextReturnTemp();
          buf.writeln(
            '$pad$returnCType $temp = (${_cType(resultType)}){ '
            '.is_err = false, .u.ok = $propagated.u.ok };',
          );
          _emitExitCleanups(
            buf,
            state.deferStack,
            sourcePath,
            indent: indent,
            bareReturnAsZero: bareReturnAsZero,
            returnCType: returnCType,
            state: state,
          );
          buf.writeln('${pad}return $temp;');
          return;
        }
        final temp = state.nextReturnTemp();
        final valueType = value.resolvedType;
        final returnValue = valueType is ResultType
            ? _emitExpr(value, ctx)
            : returnCType.startsWith('klin_res_')
                ? '($returnCType){ .is_err = false, .u.ok = ${_emitExpr(value, ctx)} }'
                : _emitExpr(value, ctx);
        buf.writeln('$pad$returnCType $temp = $returnValue;');
        _emitExitCleanups(
          buf,
          state.deferStack,
          sourcePath,
          indent: indent,
          bareReturnAsZero: bareReturnAsZero,
          returnCType: returnCType,
          state: state,
        );
        buf.writeln('${pad}return $temp;');
      }

    case BreakStmt(:final pos):
      _line(buf, pos.line, sourcePath);
      _emitLoopExitCleanups(
        buf,
        state,
        sourcePath,
        indent: indent,
        bareReturnAsZero: bareReturnAsZero,
        returnCType: returnCType,
      );
      buf.writeln('${pad}break;');

    case ContinueStmt(:final pos):
      _line(buf, pos.line, sourcePath);
      _emitLoopExitCleanups(
        buf,
        state,
        sourcePath,
        indent: indent,
        bareReturnAsZero: bareReturnAsZero,
        returnCType: returnCType,
      );
      buf.writeln('${pad}continue;');

    case DeferStmt(:final body):
      // Register at the defer site: earlier exits must not see later defers.
      if (state.deferStack.isEmpty) {
        throw StateError('emit: `defer` outside a block');
      }
      state.deferStack.last.defers.add(body);

    case BlockStmt(:final block):
      _line(buf, block.pos.line, sourcePath);
      buf.writeln('$pad{');
      _emitBlock(
        buf,
        block,
        sourcePath,
        indent: indent + 1,
        bareReturnAsZero: bareReturnAsZero,
        returnCType: returnCType,
        state: state,
      );
      buf.writeln('$pad}');

    case MatchStmt(:final pos):
      _line(buf, pos.line, sourcePath);
      _emitMatchStmt(
        buf,
        stmt,
        sourcePath,
        indent: indent,
        pad: pad,
        bareReturnAsZero: bareReturnAsZero,
        returnCType: returnCType,
        state: state,
      );
  }
}

/// Lowers a `match` statement to an `if`/`else if`/`else` chain. The subject
/// is evaluated once into a fresh temp so patterns with multiple values or
/// ranges don't re-evaluate it — zero runtime overhead beyond a plain `if`.
void _emitMatchStmt(
  StringBuffer buf,
  MatchStmt stmt,
  String sourcePath, {
  required int indent,
  required String pad,
  required bool bareReturnAsZero,
  required String returnCType,
  required _EmitState state,
}) {
  final ctx = _ExprCtx(
    buf: buf,
    sourcePath: sourcePath,
    indent: indent,
    bareReturnAsZero: bareReturnAsZero,
    returnCType: returnCType,
    state: state,
  );
  final subjectType = stmt.subject.resolvedType!;
  final temp = state.nextValueTemp();
  buf.writeln(
      '$pad${_cDecl(subjectType, temp)} = ${_emitExpr(stmt.subject, ctx)};');
  for (var i = 0; i < stmt.arms.length; i++) {
    final arm = stmt.arms[i];
    final isElse = arm.pattern is ElsePattern;
    if (i == 0) {
      buf.writeln(isElse
          ? '$pad{'
          : '${pad}if (${_patternCond(temp, arm.pattern, ctx)}) {');
    } else {
      buf.writeln(isElse
          ? '$pad} else {'
          : '$pad} else if (${_patternCond(temp, arm.pattern, ctx)}) {');
    }
    _emitBlock(
      buf,
      arm.body,
      sourcePath,
      indent: indent + 1,
      bareReturnAsZero: bareReturnAsZero,
      returnCType: returnCType,
      state: state,
    );
  }
  buf.writeln('$pad}');
}

/// Lowers a `match` expression's assignment: the subject is evaluated once,
/// then each arm assigns `target` inside its own `if`/`else if`/`else` branch
/// (reusing [_emitValueAssignment] so an arm body may itself be `or {}`/`!`).
void _emitMatchAssign(
  StringBuffer buf, {
  required String target,
  required KlinType targetType,
  required MatchExpr match,
  required String sourcePath,
  required int indent,
  required bool bareReturnAsZero,
  required String returnCType,
  required _EmitState state,
}) {
  final ctx = _ExprCtx(
    buf: buf,
    sourcePath: sourcePath,
    indent: indent,
    bareReturnAsZero: bareReturnAsZero,
    returnCType: returnCType,
    state: state,
  );
  final pad = '    ' * indent;
  final subjectType = match.subject.resolvedType!;
  final temp = state.nextValueTemp();
  buf.writeln(
      '$pad${_cDecl(subjectType, temp)} = ${_emitExpr(match.subject, ctx)};');
  for (var i = 0; i < match.arms.length; i++) {
    final arm = match.arms[i];
    final isElse = arm.pattern is ElsePattern;
    if (i == 0) {
      buf.writeln(isElse
          ? '$pad{'
          : '${pad}if (${_patternCond(temp, arm.pattern, ctx)}) {');
    } else {
      buf.writeln(isElse
          ? '$pad} else {'
          : '$pad} else if (${_patternCond(temp, arm.pattern, ctx)}) {');
    }
    _emitValueAssignment(
      buf,
      target: target,
      targetType: targetType,
      value: arm.body,
      sourcePath: sourcePath,
      indent: indent + 1,
      bareReturnAsZero: bareReturnAsZero,
      returnCType: returnCType,
      state: state,
    );
  }
  buf.writeln('$pad}');
}

String _patternCond(String temp, MatchPattern pattern, _ExprCtx ctx) {
  return switch (pattern) {
    LitPattern(:final values) =>
      values.map((v) => '$temp == ${_emitExpr(v, ctx)}').join(' || '),
    RangePattern(:final start, :final endInclusive) =>
      '($temp >= ${_emitExpr(start, ctx)} && $temp <= ${_emitExpr(endInclusive, ctx)})',
    ElsePattern() =>
      throw StateError('emit: `else` pattern has no condition'),
  };
}

void _emitFrameCleanups(
  StringBuffer buf,
  _DeferFrame frame,
  String sourcePath, {
  required int indent,
  required bool bareReturnAsZero,
  required String returnCType,
  required _EmitState state,
}) {
  final pad = '    ' * indent;
  for (final body in frame.defers.reversed) {
    _emitStmt(
      buf,
      body,
      sourcePath,
      indent: indent,
      pad: pad,
      bareReturnAsZero: bareReturnAsZero,
      returnCType: returnCType,
      state: state,
    );
  }
}

void _emitExitCleanups(
  StringBuffer buf,
  Iterable<_DeferFrame> frames,
  String sourcePath, {
  required int indent,
  required bool bareReturnAsZero,
  required String returnCType,
  required _EmitState state,
}) {
  for (final frame in frames.toList().reversed) {
    _emitFrameCleanups(
      buf,
      frame,
      sourcePath,
      indent: indent,
      bareReturnAsZero: bareReturnAsZero,
      returnCType: returnCType,
      state: state,
    );
  }
}

void _emitLoopExitCleanups(
  StringBuffer buf,
  _EmitState state,
  String sourcePath, {
  required int indent,
  required bool bareReturnAsZero,
  required String returnCType,
}) {
  final frames = <_DeferFrame>[];
  for (final frame in state.deferStack.reversed) {
    frames.add(frame);
    if (frame.isLoopBody) break;
  }
  _emitExitCleanups(
    buf,
    frames.reversed,
    sourcePath,
    indent: indent,
    bareReturnAsZero: bareReturnAsZero,
    returnCType: returnCType,
    state: state,
  );
}

void _emitElse(
  StringBuffer buf,
  Stmt? elseBranch,
  String sourcePath, {
  required int indent,
  required String pad,
  required bool bareReturnAsZero,
  required String returnCType,
  required _EmitState state,
}) {
  final ctx = _ExprCtx(
    buf: buf,
    sourcePath: sourcePath,
    indent: indent,
    bareReturnAsZero: bareReturnAsZero,
    returnCType: returnCType,
    state: state,
  );
  if (elseBranch == null) {
    buf.writeln('$pad}');
    return;
  }
  if (elseBranch is IfStmt) {
    _line(buf, elseBranch.pos.line, sourcePath);
    buf.writeln('$pad} else if (${_emitExpr(elseBranch.cond, ctx)}) {');
    _emitBlock(
      buf,
      elseBranch.thenBlock,
      sourcePath,
      indent: indent + 1,
      bareReturnAsZero: bareReturnAsZero,
      returnCType: returnCType,
      state: state,
    );
    _emitElse(
      buf,
      elseBranch.elseBranch,
      sourcePath,
      indent: indent,
      pad: pad,
      bareReturnAsZero: bareReturnAsZero,
      returnCType: returnCType,
      state: state,
    );
    return;
  }
  if (elseBranch is BlockStmt) {
    buf.writeln('$pad} else {');
    _emitBlock(
      buf,
      elseBranch.block,
      sourcePath,
      indent: indent + 1,
      bareReturnAsZero: bareReturnAsZero,
      returnCType: returnCType,
      state: state,
    );
    buf.writeln('$pad}');
    return;
  }
  throw StateError('emit: unexpected else branch ${elseBranch.runtimeType}');
}

bool _exprIsPtrReceiver(Expr expr) {
  var current = expr;
  while (current is GroupExpr) {
    current = current.inner;
  }
  return current is NameExpr && current.isPtrReceiver;
}

String _emitExpr(Expr expr, _ExprCtx ctx) {
  final raw = _emitExprRaw(expr, ctx);
  final from = expr.arrayToSliceFrom;
  if (from != null) {
    final elem = from.elem;
    if (elem is! PrimType) {
      throw StateError(
          'emit: array-to-slice conversion requires a primitive type');
    }
    return '(${_sliceCName(elem)}){ $raw, ${from.len} }';
  }
  return raw;
}

String _emitExprRaw(Expr expr, _ExprCtx ctx) {
  return switch (expr) {
    IntLit(:final lexeme) => lexeme.replaceAll('_', ''),
    FloatLit(:final lexeme) => lexeme.replaceAll('_', ''),
    BoolLit(:final value) => value ? 'true' : 'false',
    StringLit(:final value) => '"${_escapeC(value)}"',
    NameExpr(:final name, :final resolvedFnCName) =>
      resolvedFnCName ?? name,
    FieldExpr(:final object, :final name) => () {
        final objectType = object.resolvedType;
        if (name == 'len' && objectType is ArrayType) {
          return objectType.len.toString();
        }
        return _exprIsPtrReceiver(object)
            ? '${_emitExpr(object, ctx)}->$name'
            : '${_emitExpr(object, ctx)}.$name';
      }(),
    MethodCallExpr(
      :final receiver,
      :final args,
      :final mangledName,
      :final receiverByRef,
    ) =>
      '${mangledName ?? (throw StateError('emit: method without mangling'))}'
          '(${receiverByRef ? '&' : ''}${_emitExpr(receiver, ctx)}'
          '${args.isEmpty ? '' : ', ${args.map((arg) => _emitExpr(arg, ctx)).join(', ')}'})',
    StructLitExpr(
      :final resolvedType,
      :final typeName,
      :final namedFields,
      :final positionalFields
    ) =>
      namedFields != null
          ? '(${_cType(resolvedType ?? (throw StateError('emit: literal without type `$typeName`')))}){ ${namedFields.entries.map((entry) => '.${entry.key} = ${_emitExpr(entry.value, ctx)}').join(', ')} }'
          : '(${_cType(resolvedType ?? (throw StateError('emit: literal without type `$typeName`')))}){ ${positionalFields!.map((field) => _emitExpr(field, ctx)).join(', ')} }',
    CallExpr(:final callee, :final args, :final resolvedCallee) =>
      args.length == 1 && args[0] is InterpolatedStringExpr
          ? _emitInterpPrintfExpr(args[0] as InterpolatedStringExpr, ctx)
          : '${resolvedCallee ?? callee}(${args.map((arg) => _emitExpr(arg, ctx)).join(', ')})',
    InterpolatedStringExpr() => throw StateError(
        'emit: interpolated string must be lowered via printf sink',
      ),
    UnaryExpr(:final op, :final operand) => '$op(${_emitExpr(operand, ctx)})',
    IndexExpr(:final object, :final index) => object.resolvedType is SliceType
        ? '${_emitExpr(object, ctx)}.ptr[${_emitExpr(index, ctx)}]'
        : '${_emitExpr(object, ctx)}[${_emitExpr(index, ctx)}]',
    SliceFromExpr(:final array) => () {
        final type = array.resolvedType;
        if (type is! ArrayType) {
          throw StateError('emit: `[:]` without an array type');
        }
        final elem = type.elem;
        if (elem is! PrimType) {
          throw StateError('emit: slice has a non-primitive element type');
        }
        return '(${_sliceCName(elem)}){ ${_emitExpr(array, ctx)}, ${type.len} }';
      }(),
    ArrayLitExpr(:final elements) =>
      '{ ${elements.map((element) => _emitExpr(element, ctx)).join(', ')} }',
    CastExpr(:final resolvedType, :final expr) => () {
        if (resolvedType is! PtrType) {
          throw StateError('emit: cast without pointer type');
        }
        return '(${_cType(resolvedType)})(uintptr_t)(${_emitExpr(expr, ctx)})';
      }(),
    BinaryExpr(:final left, :final op, :final right) =>
      '(${_emitExpr(left, ctx)} $op ${_emitExpr(right, ctx)})',
    GroupExpr(:final inner) => '(${_emitExpr(inner, ctx)})',
    ErrorExpr(:final code, :final resolvedType) => () {
        if (resolvedType is! ResultType) {
          throw StateError('emit: `error` without a result type');
        }
        return '(${_cType(resolvedType)}){ .is_err = true, .u.err = ${_emitExpr(code, ctx)} }';
      }(),
    PropagateExpr(:final result) => () {
        final temp = _emitPropagate(result, ctx);
        return '$temp.u.ok';
      }(),
    OrExpr(:final resolvedType) => () {
        final outType = resolvedType;
        if (outType == null) {
          throw StateError('emit: `or` without an expression result type');
        }
        final out = ctx.state.nextValueTemp();
        final pad = '    ' * ctx.indent;
        ctx.buf.writeln('$pad${_cType(outType)} $out;');
        _emitValueAssignment(
          ctx.buf,
          target: out,
          targetType: outType,
          value: expr,
          sourcePath: ctx.sourcePath,
          indent: ctx.indent,
          bareReturnAsZero: ctx.bareReturnAsZero,
          returnCType: ctx.returnCType,
          state: ctx.state,
        );
        return out;
      }(),
    MatchExpr(:final resolvedType) => () {
        final outType = resolvedType;
        if (outType == null) {
          throw StateError('emit: `match` without an expression result type');
        }
        final out = ctx.state.nextValueTemp();
        final pad = '    ' * ctx.indent;
        ctx.buf.writeln('$pad${_cType(outType)} $out;');
        _emitMatchAssign(
          ctx.buf,
          target: out,
          targetType: outType,
          match: expr,
          sourcePath: ctx.sourcePath,
          indent: ctx.indent,
          bareReturnAsZero: ctx.bareReturnAsZero,
          returnCType: ctx.returnCType,
          state: ctx.state,
        );
        return out;
      }(),
  };
}

String _structCName(String module, String name) =>
    module.isEmpty ? name : '${module}_$name';

String _freeCName(String module, String name) =>
    module.isEmpty ? name : '${module}_$name';

String _methodCName(String module, String type, String method) =>
    module.isEmpty ? '${type}_$method' : '${module}_${type}_$method';

void _line(StringBuffer buf, int line, String path) {
  buf.writeln('#line $line "${_escapeC(path)}"');
}

String _escapeC(String s) {
  final out = StringBuffer();
  for (final cu in s.runes) {
    switch (cu) {
      case 0x0A: // \n
        out.write('\\n');
      case 0x09: // \t
        out.write('\\t');
      case 0x22: // "
        out.write('\\"');
      case 0x5C: // \
        out.write('\\\\');
      default:
        if (cu < 0x20 || cu == 0x7F) {
          out.write('\\x${cu.toRadixString(16).padLeft(2, '0')}');
        } else {
          out.writeCharCode(cu);
        }
    }
  }
  return out.toString();
}
